baseURL = 'https://0xkylm.github.io'
languageCode = 'en-us'
title = 'KylmBlog'
theme = 'paper'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  twitter = '0xkylm'    
  github = '0xkylm'    

  avatar = 'https://avatars.githubusercontent.com/u/94079228?s=400&u=0fe4142bcd24004f9f3af6cde4dbdac3be9542c9&v=4'                 # gravatar email or image url
  name = 'Kylm'
  bio = 'French student, internship @ Fuzzinglabs,  Interested in vr,ed and maldev'


[menu]

  [[menu.main]]
    identifier = "CoolPeople"
    name = "CoolPeople"
    url = "/Friends/"
    weight = 10

